"use client";

import { ArrowUpRight, Download, RefreshCw, ScanLine } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { formatEventDate, formatShortTime, type EventStats } from "@/lib/event-types";
import { AiInsightBox } from "@/components/ai-insight-box";

export function EventOverview({ eventId, initialStats }: { eventId: string; initialStats: EventStats }) {
  const [stats, setStats] = useState(initialStats);
  const [refreshing, setRefreshing] = useState(false);
  const refresh = useCallback(async () => { setRefreshing(true); const response = await fetch(`/api/events/${eventId}/stats`, { cache: "no-store" }); if (response.ok) { const body = await response.json(); setStats(body.stats); } setRefreshing(false); }, [eventId]);
  useEffect(() => { const supabase = createClient(); const channel = supabase.channel(`event-${eventId}-overview`).on("postgres_changes", { event: "*", schema: "public", table: "events", filter: `id=eq.${eventId}` }, refresh).on("postgres_changes", { event: "*", schema: "public", table: "registrations", filter: `event_id=eq.${eventId}` }, refresh).on("postgres_changes", { event: "*", schema: "public", table: "checkins" }, refresh).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [eventId, refresh]);
  return <><div className="event-title-row"><div><span className="eyebrow">{formatEventDate(stats.starts_at)}</span><h1>{stats.name}</h1><p>{stats.location} · {stats.description || "No event description."}</p></div><div className="event-actions"><button className="button button-quiet" onClick={refresh} disabled={refreshing}><RefreshCw size={15} className={refreshing ? "spin" : ""} /> Refresh</button><a className="button button-outline" href={`/api/events/${eventId}/export`}><Download size={15} /> CSV</a><Link className="button button-dark" href={`/scan/${eventId}`}><ScanLine size={15} /> Open scanner</Link></div></div><section className="metric-grid"><div className="metric-card"><span>Registered</span><strong>{stats.registered_count}</strong><small>Capacity {stats.capacity}</small></div><div className="metric-card"><span>Checked in</span><strong>{stats.checked_in_count}</strong><small>{stats.arrival_rate}% arrival rate</small></div><div className="metric-card"><span>Spots left</span><strong>{stats.spots_left}</strong><small>{stats.no_shows} not checked in yet</small></div></section><div className="overview-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Recent arrivals</span><h2>Who is in the room.</h2></div><Link className="text-link" href={`/events/${eventId}/check-ins`}>Full check-ins <ArrowUpRight size={15} /></Link></div>{stats.recent_arrivals.length ? <div className="arrival-list">{stats.recent_arrivals.map((arrival) => <div className="arrival-row" key={arrival.id}><span className="avatar avatar-small">{arrival.display_name.slice(0, 1).toUpperCase()}</span><span><strong>{arrival.display_name}</strong><small>{arrival.email}</small></span><time>{formatShortTime(arrival.checkins[0]?.checked_in_at || null)}</time></div>)}</div> : <div className="quiet-note">No check-ins recorded yet. The next accepted scan will appear here.</div>}</section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Desk signal</span><h2>Operational read.</h2></div></div><div className="signal-list"><div><span>Latest check-in</span><strong>{formatShortTime(stats.latest_checkin_at)}</strong></div><div><span>Remaining capacity</span><strong>{stats.spots_left} places</strong></div><div><span>Data source</span><strong>Supabase + Realtime</strong></div></div></section></div><AiInsightBox eventId={eventId} /></>;
}
